### PR TITLE
[MASTER] Deprecation Warning

### PR DESCRIPTION
**Pull request by HugoPouliquen**
DEPRECATION WARNING : Active Admin: using  without a name is deprecated! Use . (called from action_item at ~/.bundler/ruby/2.1.5/active_admin-add0928290f3/lib

### CODE REVIEW

**Comment by macfanatic** [comment]
Thanks @HugoPouliquen  - I think the identifiers has to be unique, which would cause failures if you used `state_action` more than once for a resource.

What do you think about simply using the `action` name, such as:

```ruby
action_item "state_action_#{ action }", only: :show
```

**Comment by HugoPouliquen** [comment]
Thanks @macfanatic for your proposition, I have added this in my PR

I hadded fixed to launch rspec too.

**Comment by HugoPouliquen** [comment]
@macfanatic I have added support to active admin 0.6.6 and less. Last commit were only working for active admin 1.0.0.

**Comment by macfanatic** [comment]
Thanks for those changes!

**Pull request merged**
